import { Header } from "../Header/Header";
import Head from "next/head";
import { Hero } from "../Hero/Hero";
import { Navigation } from "../Navigation/Navigation";

export const Layout = ({ children, title = "ДЮСШ №1" }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      </Head>
      <Header />
      <main>
        <Hero />
        <Navigation />
        {children}
      </main>
    </>
  );
};
