import { Header } from "../Header/Header";
import Head from "next/head";
import { Hero } from "../Hero/Hero";
import { Navigation } from "../Navigation/Navigation";
import { Footer } from "../Footer/Fotter";

export const Layout = ({ children, title = "ДЮСШ №1", main }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Hero />
        <Navigation main={main} />
        <div
          style={{
            backgroundImage: "url(/background.jpeg)",
            backgroundRepeat: "no-repeat",
            backgroundSize: "cover",
            backgroundAttachment: "fixed",
          }}
        >
          {children}
        </div>
      </main>
      <Footer />
    </>
  );
};
